package roiderUnion.ids

object Aliases {
    const val PREFIX = "roider_"
    const val SAVEBREAK = PREFIX + "savebreak_"
    const val PIRLRNBP = PREFIX + "pirLrnBP"
    const val DIVESC = PREFIX + "divesC"
    const val DIVESM = PREFIX + "divesM"
    const val DIVESV = PREFIX + "divesV"
    const val DIVESI = PREFIX + "divesI"
    const val DIVESSI = PREFIX + "divesSI"
    const val SW = PREFIX + "sw"
    const val HQBP = PREFIX + "hqBP"
    const val SWBP = PREFIX + "swBP"
    const val HQPMAN = PREFIX + "hqPMan"
    const val RETBP = PREFIX + "retBP"
    const val NOMMARK = PREFIX + "nomMark"
    const val MAJLOOT = PREFIX + "majLoot"
    const val PNGTRP = PREFIX + "pngTrp"
    const val SYSMUSIC = PREFIX + "sysMusic"
    const val AABIL = PREFIX + "aAbil"
    const val AABILADD = PREFIX + "aAbilAdd"
    const val ARMBPADDER = PREFIX + "armBPAdder"
    const val MADHLR = PREFIX + "madHlr"
    const val ND = PREFIX + "nd"
    const val NBSPAWN = PREFIX + "nBSpawn"
    const val NWARNTAG = PREFIX + "nWarnTag"
    const val SPLYSCRIPT = PREFIX + "splyScript"
    const val NLVLER = PREFIX + "nLvler"
    const val NBIC = PREFIX + "nBIC"
    const val NBIM = PREFIX + "nBIM"
    const val NBIV = PREFIX + "nBIV"
    const val NBII = PREFIX + "nBII"
    const val RRZ = PREFIX + "rRZ"
}